-- CreateEnum
CREATE TYPE "RESTAURANT_STATUS" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

-- AlterTable
ALTER TABLE "Restaurant" ADD COLUMN     "status" "RESTAURANT_STATUS" NOT NULL DEFAULT 'PENDING';
